@echo off
set "DB_URL=jdbc:postgresql://db.zwhhljorbjwueldcewmt.supabase.co:5432/postgres?sslmode=require"
set "DB_USERNAME=postgres"
set "DB_PASSWORD=BizFlow@2006"
set "SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=5"
set "SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=1"
set "SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000"
set "OPENROUTER_MODEL=meta-llama/llama-3.3-70b-instruct"
set "GEMINI_MODEL=gemini-1.5-flash"
set "SPRING_PROFILES_ACTIVE=dev"
.\mvnw.cmd spring-boot:run
