@echo off
set "DB_URL=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0"
set "DB_USERNAME=postgres.zwhhljorbjwueldcewmt"
set "DB_PASSWORD=BizFlow@2006"
set "SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=5"
set "SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=1"
set "SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000"
set "SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000"
set "SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000"
set "OPENROUTER_MODEL=meta-llama/llama-3.3-70b-instruct"
set "GEMINI_MODEL=gemini-1.5-flash"
set "SPRING_PROFILES_ACTIVE=dev"
.\mvnw.cmd spring-boot:run
